# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Ultraclr"
repo_name: "agents-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/agents-arxiv-daily.json'
json_gitpage_path: './docs/agents-arxiv-daily-web.json'
json_wechat_path: './docs/agents-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Agent":
        filters: ["intelligent agent", "AI agent", "LLM agent framework", "agent memory", "agent emotion" "autonomous agent", "agent system framework", "Foudation Agents", "agent benchmark", "agent evaluation framework", "AgentBench", "LLM agent benchmark"]
    "Multi-Agent":
        filters: ["multi-agent system", "agent collaboration"]
    "RL":
        filters: ["Reinforcement Learning for AI Agent"]
